overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  playwright@<1.55.1: '>=1.55.1'
  prismjs@<1.30.0: '>=1.30.0'
